apiVersion: v1
kind: ServiceAccount
metadata:
  name: book-service
  namespace: bookstore
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::016257615899:role/book-service-s3-access
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      serviceAccountName: book-service
      containers:
        - name: book-service
          image: 016257615899.dkr.ecr.us-west-2.amazonaws.com/book-service:fadf193
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "5"
            - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
              value: "2"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: DB_URL
              value: "jdbc:mysql://bookstore-postgres.cdu60wwkywed.us-west-2.rds.amazonaws.com:3306/bookstore_books_db?serverTimezone=UTC"
            - name: DB_HOST
              value: "bookstore-postgres.cdu60wwkywed.us-west-2.rds.amazonaws.com"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: JWT_SECRET
              value: "3b796f1d-02e9-4263-a411-ceb6e5532239"
            - name: S3_BUCKET_NAME
              value: "bookstore-book-images-016257615899"
            - name: AWS_REGION
              value: "us-west-2"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
  namespace: bookstore
spec:
  selector:
    app: book-service
  ports:
    - port: 8083
      targetPort: 8083
  type: ClusterIP