apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prometheus
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ashishnamdeo16/bookstore-infra.git
    path: k8s/monitoring/prometheus
    targetRevision: main
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ashishnamdeo16/bookstore-infra.git
    path: k8s/monitoring/grafana
    targetRevision: main
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-alertmanager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ashishnamdeo16/bookstore-infra.git
    path: k8s/monitoring/alertmanager
    targetRevision: main
    directory:
      recurse: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true