apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: 016257615899.dkr.ecr.us-west-2.amazonaws.com/user-service:fadf193
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "5"
            - name: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
              value: "2"
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: DB_URL
              value: "jdbc:mysql://bookstore-postgres.cdu60wwkywed.us-west-2.rds.amazonaws.com:3306/bookstore_user_db?serverTimezone=UTC"
            - name: DB_HOST
              value: "bookstore-postgres.cdu60wwkywed.us-west-2.rds.amazonaws.com"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
            - name: JWT_SECRET
              value: "3b796f1d-02e9-4263-a411-ceb6e5532239"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: bookstore
spec:
  selector:
    app: user-service
  ports:
    - port: 8082
      targetPort: 8082
  type: ClusterIP
